removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

player forceAddUniform 'rhs_uniform_afghanka';
for '_i' from 1 to 5 do { player addItemToUniform 'ACE_elasticBandage';};
for '_i' from 1 to 5 do { player addItemToUniform 'ACE_packingBandage';};
for '_i' from 1 to 5 do { player addItemToUniform 'ACE_fieldDressing';};
player addItemToUniform 'ACE_EarPlugs';
for '_i' from 1 to 2 do { player addItemToUniform 'ACE_morphine';};
player addVest 'rhs_6b23_ML_6sh92';
for '_i' from 1 to 6 do { player addItemToVest 'rhs_10Rnd_762x54mmR_7N14';};
for '_i' from 1 to 2 do { player addItemToVest 'ACE_10Rnd_762x54_Tracer_mag';};
for '_i' from 1 to 2 do { player addItemToVest 'rhs_mag_rgd5';};
for '_i' from 1 to 2 do { player addItemToVest 'wog_mag_rdgm_white';};
player addBackpack 'rhs_sidor';
player addWeapon 'CUP_srifle_SVD';
player addPrimaryWeaponItem 'rhs_acc_pso1m2';
player addHeadgear 'rhs_6b7_1m_ess';
player linkItem 'ItemMap';
player linkItem 'ItemGPS';
player linkItem 'ItemCompass';
player linkItem 'tf_fadak';
player addWeapon 'Binocular';
