removeAllWeapons player;
removeAllItems player;
removeAllAssignedItems player;
removeUniform player;
removeVest player;
removeBackpack player;
removeHeadgear player;
removeGoggles player;

player forceAddUniform 'rhs_uniform_afghanka';
for '_i' from 1 to 5 do { player addItemToUniform 'ACE_elasticBandage';};
for '_i' from 1 to 5 do { player addItemToUniform 'ACE_packingBandage';};
for '_i' from 1 to 5 do { player addItemToUniform 'ACE_fieldDressing';};
player addItemToUniform 'ACE_EarPlugs';
for '_i' from 1 to 2 do { player addItemToUniform 'ACE_morphine';};
player addVest 'rhs_6b23_ML_6sh92';
for '_i' from 1 to 6 do { player addItemToVest 'rhs_30Rnd_545x39_7N6_AK';};
for '_i' from 1 to 2 do { player addItemToVest 'rhs_30Rnd_545x39_AK_green';};
for '_i' from 1 to 2 do { player addItemToVest 'rhs_mag_rgd5';};
for '_i' from 1 to 2 do { player addItemToVest 'wog_mag_rdgm_white';};
player addBackpack 'rhs_sidor';
for '_i' from 1 to 5 do { player addItemToBackpack  'ACE_adenosine';};
for '_i' from 1 to 10 do { player addItemToBackpack  'ACE_epinephrine';};
for '_i' from 1 to 10 do { player addItemToBackpack  'ACE_morphine';};
for '_i' from 1 to 10 do { player addItemToBackpack  'ACE_tourniquet';};
for '_i' from 1 to 10 do { player addItemToBackpack  'ACE_splint';};
for '_i' from 1 to 15 do { player addItemToBackpack  'ACE_quikclot';};
for '_i' from 1 to 15 do { player addItemToBackpack  'ACE_fieldDressing';};
for '_i' from 1 to 15 do { player addItemToBackpack  'ACE_elasticBandage';};
for '_i' from 1 to 15 do { player addItemToBackpack  'ACE_packingBandage';};
for '_i' from 1 to 5 do { player addItemToBackpack  'ACE_salineIV_500';};
for '_i' from 1 to 5 do { player addItemToBackpack  'ACE_bloodIV_500';};
player addWeapon 'rhs_weap_ak74';
player addHeadgear 'rhs_6b7_1m_ess';
player linkItem 'ItemMap';
player linkItem 'ItemGPS';
player linkItem 'ItemCompass';
player linkItem 'tf_fadak';
player addWeapon 'Binocular';

